<?php
return array (
  'version' => array(  
    'app' => array(    
      'default' => array(      
        0 => '001_create_core_configuration_tables',
        1 => '002_add_company_configuration_fields',
        2 => '003_create_core_web_tables',
        3 => '004_create_core_legal_tables',
        4 => '005_create_core_communication_tables',
        5 => '006_create_core_sat_tables',
        6 => '007_create_core_catalog_tables',
        7 => '008_create_core_commerce_catalog_tables',
        8 => '009_create_core_commerce_price_tables',
        9 => '010_create_core_sat_catalog_tables',
        10 => '011_create_core_frontend_tables',
        11 => '012_create_core_frontend_theme_tables',
        12 => '013_create_core_knowledge_tables',
        13 => '014_create_core_operational_catalog_tables',
        14 => '015_create_core_party_tables',
        15 => '016_create_core_portal_access_tables',
        16 => '017_create_core_document_tables',
        17 => '018_create_core_helpdesk_tables',
        18 => '019_create_core_integration_audit_tables',
        19 => '020_create_core_payment_bank_tables',
        20 => '021_create_core_billing_tables',
        21 => '022_enhance_core_sat_cfdi_validation',
        22 => '023_enhance_core_audit_logs',
        23 => '024_create_core_calendar_tables',
        24 => '025_create_core_cart_tables',
        25 => '026_create_core_sales_quote_tables',
        26 => '027_add_frontend_theme_seo_fields',
        27 => '028_create_core_commerce_product_relations',
        28 => '029_create_core_purchase_tables',
        29 => '030_extend_core_sat_cfdi_audit_tables',
        30 => '031_add_cfdi_party_scope_controls',
        31 => '032_enhance_sat_credentials_cert_files',
        32 => '033_add_supplier_onboarding_fields',
        33 => '034_enhance_purchase_approval_flow',
        34 => '035_add_offline_sales_support',
        35 => '036_enhance_frontend_footer_cms',
        36 => '037_add_commerce_stock_quote_fields',
        37 => '038_enhance_billing_pac_cfdi',
        38 => '039_create_sales_delivery_inventory_flow',
        39 => '040_create_inventory_stock_balances',
        40 => '041_create_purchase_cfdi_line_mappings',
        41 => '042_create_core_accounting_tables',
        42 => '043_create_core_crm_tables',
        43 => '044_create_billing_recurring_and_service_products',
        44 => '045_create_core_fiscal_documents',
      ),
    ),
    'module' => array(    
    ),
    'package' => array(    
      'auth' => array(      
        0 => '001_auth_create_usertables',
        1 => '002_auth_create_grouptables',
        2 => '003_auth_create_roletables',
        3 => '004_auth_create_permissiontables',
        4 => '005_auth_create_authdefaults',
        5 => '006_auth_add_authactions',
        6 => '007_auth_add_permissionsfilter',
        7 => '008_auth_create_providers',
        8 => '009_auth_create_oauth2tables',
        9 => '010_auth_fix_jointables',
        10 => '011_auth_group_optional',
        11 => '012_auth_update_userindex',
      ),
    ),
  ),
  'folder' => 'migrations/',
  'table' => 'migration',
  'flush_cache' => false,
  'flag' => NULL,
);
