<?php

class Model_Core_Sat_Cfdi extends \Orm\Model
{
    protected static $_table_name = 'core_sat_cfdi';
    protected static $_primary_key = ['id'];

    protected static $_properties = [
        'id',
        'uuid',
        'direction',
        'version',
        'serie',
        'folio',
        'emitter_rfc',
        'emitter_party_id',
        'emitter_name',
        'emitter_regime',
        'receiver_rfc',
        'receiver_party_id',
        'customer_party_id',
        'supplier_party_id',
        'receiver_name',
        'receiver_regime',
        'receiver_zip',
        'issued_at',
        'stamped_at',
        'total',
        'subtotal',
        'discount',
        'tax_transferred_total',
        'tax_withheld_total',
        'currency',
        'exchange_rate',
        'voucher_type',
        'export_code',
        'place_of_issue',
        'payment_method',
        'payment_form',
        'conditions_payment',
        'certificate_number',
        'certificate_sat_number',
        'pac_rfc',
        'seal_cfdi',
        'seal_sat',
        'cfdi_use',
        'sat_status',
        'sat_status_code',
        'sat_status_message',
        'cancelled_at',
        'last_validated_at',
        'metadata_seen_at',
        'missing_xml',
        'complements_json',
        'has_payment_complement',
        'has_waybill',
        'sales_status',
        'purchase_status',
        'portal_visible_customer',
        'portal_visible_supplier',
        'reviewed_by',
        'reviewed_at',
        'origin',
        'processed',
        'accounted',
        'xml_path',
        'created_at',
        'updated_at',
    ];

    protected static $_observers = [
        'Orm\Observer_CreatedAt' => [
            'events' => ['before_insert'],
            'property' => 'created_at',
            'mysql_timestamp' => false,
        ],
        'Orm\Observer_UpdatedAt' => [
            'events' => ['before_save'],
            'property' => 'updated_at',
            'mysql_timestamp' => false,
        ],
    ];
}
